services:
  api:
    build:
      context: ./referral_system
      dockerfile: Dockerfile
    ports:
      - 80:8000
    volumes:
      - ./referral_system:/app
    depends_on:
      - db
    environment:
      DEBUG: 0
      # переменные окружения для подключения к базе
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: referal_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: referal_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
