# Generated by Django 5.2.4 on 2025-07-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_referal_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='parent_referal',
            new_name='parent_referral',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='referal_number',
            new_name='referral_number',
        ),
    ]
